FROM continuumio/miniconda3


# force bash to be used instead of shell
run rm /bin/sh && ln -s /bin/bash /bin/sh
  - minimap2
  - samtools
  - hisat2
  - genometools-genometools
  - gffread

RUN conda create -n myenv -c conda-forge -c bioconda braker2 minimap2 samtools hisat2 genometools-genometools gffread && \
    echo "source activate myenv" > ~/.bashrc

ENV PATH=/KMC/bin/:$PATH


# build singularity dir structure to hopefully hack singularity functionality when relevant
run mkdir -p /.singularity.d/env
# run echo '#!/bin/bash' >> /.singularity.d/env/91-environment.sh
run echo '. /opt/conda/etc/profile.d/conda.sh' >> /.singularity.d/env/91-environment.sh
run echo 'conda activate myenv' >> /.singularity.d/env/91-environment.sh

# Make RUN commands use the new environment (for docker execution):
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]

