FROM continuumio/miniconda3

WORKDIR /app

# Create the environment:
COPY assembly.locked.yml environment.yml
RUN conda env create -f environment.yml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]

