FROM continuumio/miniconda3

# specify  environment yml:
COPY busco_trees.yml environment.yml

# force bash to be used instead of shell
run rm /bin/sh && ln -s /bin/bash /bin/sh

# build needed env
RUN \
    . /opt/conda/etc/profile.d/conda.sh && \
    conda env create -f environment.yml -n myenv && \
    apt-get update && \
    apt-get install -y build-essential && \
    sudo apt-get install zip \
    wget https://github.com/stamatak/standard-RAxML/archive/v8.2.12.tar.gz && \
    tar -xvf v8.2.12.tar.gz && \
    rm -rf v8.2.12.tar.gz && \
    cd standard-RAxML-8.2.12/ && \
    make -f Makefile.gcc && \
    rm *.o && \
    make -f Makefile.SSE3.gcc && \
    rm *.o && \
    make -f Makefile.AVX.gcc && \
    rm *.o && \
    make -f Makefile.PTHREADS.gcc && \
    rm *.o && \
    make -f Makefile.SSE3.PTHREADS.gcc && \
    rm *.o && \
    make -f Makefile.AVX.PTHREADS.gcc && \
    rm *.o

# added conda activation to bashrc which maybe sometimes does something
RUN echo "source activate myenv" > ~/.bashrc

# build singularity dir structure to hopefully hack singularity functionality when relevant
run mkdir -p /.singularity.d/env
# run echo '#!/bin/bash' >> /.singularity.d/env/91-environment.sh
run echo '. /opt/conda/etc/profile.d/conda.sh' >> /.singularity.d/env/91-environment.sh
run echo 'conda activate myenv' >> /.singularity.d/env/91-environment.sh

# Make RUN commands use the new environment (for docker execution):
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]

